import {GenericMethods} from "../pageobjects/generic/genericMethods";
import {GenericElements} from "../pageobjects/generic/genericElements";
import {WoonVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/huisVerzekeringen/woonVerzekeringMethods";
import {WoonVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/huisVerzekeringen/woonVerzekeringElements";
import {PersonaData} from "../pageobjects/persona/persona";
import {NawElements} from "../pageobjects/generic/nawElements";
import {ApiElements} from "../pageobjects/api/apiElements";
import {GetUrlUnive} from "../pageobjects/generic/getUrlUnive";
import {HmPageElements} from "../pageobjects/generic/hmPageElements";
import {AansprakelijkheidsVerzekerElements} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/aansprakelijkheidsVerzekerElements";
import {ReisVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/reisVerzekeringElements";
import {ProductPageElements} from "../pageobjects/generic/productPageElements";
import {AovZzpElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/aovZzpElements";
import {ZakelijkRechtsBijstandVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/zakelijkRechtsBijstandVerzekeringElements";
import {EigenVervoerVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/eigenVervoerVerzekeringElements";
import {HmPageMijnUniveElements} from "../pageobjects/generic/hmPageMijnUniveElements";
import {SituatieGewijzigdElements} from "../pageobjects/Klantenservice/SituatieGewijzigdElements";
import {LoginPageElements} from "../pageobjects/mijnUniveParticulier/loginPage/loginPageElements";
import {MijnUniveAccountElements} from "../pageobjects/mijnUniveParticulier/mijnUniveAccount/mijnUniveAccountElements";
import {MijnSchadeEnClaimElements} from "../pageobjects/mijnUniveParticulier/MijnSchadeEnClaim/MijnSchadeEnClaimElements";
import {AlleVerzekeringenElements} from "../pageobjects/particuliereVerzekeringen/alleVerzekeringen/alleVerzekeringenElements";
import {OngevallenVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/gezondheidsVerzekeringen/ongevallenVerzekeringElements";
import {ZorgeloosOnlineVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/onlineVeiligheidVerzekeringen/zorgeloosOnlineVerzekeringElements";
import {RechtsBijstandVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/rechtsBijstandVerzekeringElements";
import {CarWithLicensePlate} from "../pageobjects/vehicles/carWithLicensePlate";
import {AutoVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElements";
import {AutoVerzekeringElementsStepThree} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElementsStepThree";
import {BusinessCarWithLicensePlate} from "../pageobjects/vehicles/businessCarWithLicensePlate";
import {BedrijfsAutoVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/bedrijfsAutoVerzekeringElements";
import {VehicleElements} from "../pageobjects/generic/vehicleElements";
import {MopedWithLicensePlate} from "../pageobjects/vehicles/mopedWithLicensePlate";
import {MotorElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/motorElements";
import {MotorWithLicensePlate} from "../pageobjects/vehicles/motorWithLicensePlate";
import {OldtimerVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/oldtimerVerzekeringElements";
import {BootVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/bootVerzekeringElements";
import {CamperVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/camperVerzekeringElements";
import {CamperWithLicensePlate} from "../pageobjects/vehicles/camperWithLicensePlate";
import {AlleVerzekeringenZakelijkElements} from "../pageobjects/zakelijkeVerzekeringen/alleVerzekeringen/alleVerzekeringenZakelijkElements";
import {ZakelijkAansprakelijkheidsVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/zakelijkAansprakelijkheidsVerzekeringElements";
import {RoerendeZakenVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsMiddelenVerzekeringen/roerendeZakenVerzekeringElements";
import {ZakelijkTractorVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/zakelijkTractorVerzekeringElements";
import {ApiMethods} from "../pageobjects/api/apiMethods";
import {KlachtenFormulierElements} from "../pageobjects/Klantenservice/KlachtenFormulierElements";
import {AfspraakMakenElements} from "../pageobjects/Klantenservice/AfspraakMakenElements";
import {KlantenserviceVraagStellenElements} from "../pageobjects/Klantenservice/KlantenserviceVraagStellenElements";
import {SchadeBeslisboomElements} from "../pageobjects/Klantenservice/SchadeBeslisboomElements";
import {SituatieGewijzigdMethods} from "../pageobjects/Klantenservice/SituatieGewijzigdMethods";
import {HmPageMijnUniveMethods} from "../pageobjects/generic/hmPageMijnUniveMethods";
import {LoginPageMethods} from "../pageobjects/mijnUniveParticulier/loginPage/loginPageMethods";
import {PersoonlijkeGegevensElements} from "../pageobjects/mijnUniveParticulier/mijnGegevens/persoonlijkeGegevensElements";
import {PersoonlijkeGegevensMethods} from "../pageobjects/mijnUniveParticulier/mijnGegevens/PersoonlijkeGegevensMethods";
import {MailhogMethods} from "../pageobjects/mijnUniveParticulier/mail/MailhogMethods";
import {VerhuizingDoorgevenElements} from "../pageobjects/mijnUniveParticulier/mijnGegevens/verhuizingDoorgevenElements";
import {CorrespondentieElements} from "../pageobjects/mijnUniveParticulier/MijnPostvak/CorrespondentieElements";
import {MijnSchadeEnClaimMethods} from "../pageobjects/mijnUniveParticulier/MijnSchadeEnClaim/MijnSchadeEnClaimMethods";
import {MijnVerzekeringenElements} from "../pageobjects/mijnUniveParticulier/mijnVerzekeringen/mijnVerzekeringenElements";
import {AlleVerzekeringenMethods} from "../pageobjects/particuliereVerzekeringen/alleVerzekeringen/alleVerzekeringenMethods";
import {OngevallenVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/gezondheidsVerzekeringen/ongevallenVerzekeringMethods";
import {HmPageMethods} from "../pageobjects/generic/hmPageMethods";
import {KostbaarhedenVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/huisVerzekeringen/kostbaarhedenVerzekeringElements";
import {CompanyData} from "../pageobjects/persona/company";
import {ZorgeloosOnlineVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/onlineVeiligheidVerzekeringen/zorgeloosOnlineVerzekeringMethod";
import {AansprakelijkheidsVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/aansprakelijkheidsVerzekeringMethods";
import {RechtsBijstandVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/rechtsBijstandVerzekeringMethods";
import {MopedElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/mopedElements";
import {AutoVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringMethods";
import {AutoVerzekeringMethodsStepThreeAndFour} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringMethodsStepThreeAndFour";
import {BikeElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/bikeElements";
import {MopedMethods} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/mopedMethods";
import {LicensePlateMethod} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/licensePlateMethod";
import {MotorMethods} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/motorMethods";
import {OldtimerVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/oldtimerVerzekeringMethods";
import {ScootMobielVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/scootMobielVerzekeringElements";
import {BootVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/bootVerzekeringMethods";
import {BoatWithName} from "../pageobjects/vehicles/boatWithName";
import {CamperVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/camperVerzekeringMethods";
import {CaravanVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/caravanVerzekeringElements";
import {ReisVerzekeringMethods} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/reisVerzekeringMethods";
import {AlleVerzekeringenZakelijkMethods} from "../pageobjects/zakelijkeVerzekeringen/alleVerzekeringen/alleVerzekeringenZakelijkMethods";
import {AovZzpMethods} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/aovZzpMethods";
import {EigenVervoerVerzekeringMethods} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/eigenVervoerVerzekeringMethods";
import {RoerendeZakenVerzekeringMethods} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsMiddelenVerzekeringen/roerendeZakenVerzekeringMethods";
import {BedrijfsAutoVerzekeringMethods} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/bedrijfsAutoVerzekeringMethods";
import {ZakelijkTractorVerzekeringMethods} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/zakelijkTractorVerzekeringMethods";

export const genericMethods: GenericMethods = new GenericMethods();
export const genericElements: GenericElements = new GenericElements();
export const woonVerzekeringMethods: WoonVerzekeringMethods = new WoonVerzekeringMethods();
export const woonVerzekeringElements: WoonVerzekeringElements = new WoonVerzekeringElements();
export const personaData: PersonaData = new PersonaData();
export const nawElements: NawElements = new NawElements();
export const apiElements: ApiElements = new ApiElements();
export const getUrlUnive: GetUrlUnive = new GetUrlUnive();
export const hmPageElements: HmPageElements = new HmPageElements();
export const aansprakelijkheidsVerzekerElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const reisVerzekeringElements: ReisVerzekeringElements = new ReisVerzekeringElements();
export const productPageElements: ProductPageElements = new ProductPageElements();
export const aovZzpElements: AovZzpElements = new AovZzpElements();
export const zakelijkRechtsBijstandVerzekeringElements: ZakelijkRechtsBijstandVerzekeringElements = new ZakelijkRechtsBijstandVerzekeringElements;
export const hmPageMijnUniveElements: HmPageMijnUniveElements = new HmPageMijnUniveElements();
export const situatieGewijzigdElements: SituatieGewijzigdElements = new SituatieGewijzigdElements();
export const loginPageElements: LoginPageElements = new LoginPageElements();
export const mijnUniveAccountElements: MijnUniveAccountElements = new MijnUniveAccountElements();
export const mijnSchadeEnClaimElements: MijnSchadeEnClaimElements = new MijnSchadeEnClaimElements();
export const alleVerzekeringenElements: AlleVerzekeringenElements = new AlleVerzekeringenElements();
export const ongevallenVerzekeringElements: OngevallenVerzekeringElements = new OngevallenVerzekeringElements();
export const zorgeloosOnlineVerzekeringElements: ZorgeloosOnlineVerzekeringElements = new ZorgeloosOnlineVerzekeringElements();
export const aansprakelijkheidsVerzekeringElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const rechtsBijstandVerzekeringElements: RechtsBijstandVerzekeringElements = new RechtsBijstandVerzekeringElements();
export const carWithLicensePlate: CarWithLicensePlate = new CarWithLicensePlate();
export const autoVerzekeringElements: AutoVerzekeringElements = new AutoVerzekeringElements();
export const autoVerzekeringElementsStepThree: AutoVerzekeringElementsStepThree = new AutoVerzekeringElementsStepThree();
export const businessCarWithLicensePlate: BusinessCarWithLicensePlate = new BusinessCarWithLicensePlate();
export const bedrijfsAutoVerzekeringElements: BedrijfsAutoVerzekeringElements = new BedrijfsAutoVerzekeringElements();
export const vehicleElements: VehicleElements = new VehicleElements();
export const mopedWithLicensePlate: MopedWithLicensePlate = new MopedWithLicensePlate();
export const motorElements: MotorElements = new MotorElements();
export const oldtimerVerzekeringElements: OldtimerVerzekeringElements = new OldtimerVerzekeringElements();
export const motorWithLicensePlate: MotorWithLicensePlate = new MotorWithLicensePlate();
export const bootVerzekeringElements: BootVerzekeringElements = new BootVerzekeringElements();
export const camperVerzekeringElements: CamperVerzekeringElements = new CamperVerzekeringElements();
export const camperWithLicensePlate: CamperWithLicensePlate = new CamperWithLicensePlate();
export const alleVerzekeringenZakelijkElements: AlleVerzekeringenZakelijkElements = new AlleVerzekeringenZakelijkElements();
export const zakelijkAansprakelijkheidsVerzekeringElements: ZakelijkAansprakelijkheidsVerzekeringElements = new ZakelijkAansprakelijkheidsVerzekeringElements();
export const roerendeZakenVerzekeringElements: RoerendeZakenVerzekeringElements = new RoerendeZakenVerzekeringElements();
export const eigenVervoerVerzekeringElements: EigenVervoerVerzekeringElements = new EigenVervoerVerzekeringElements();
export const zakelijkTractorVerzekeringElements: ZakelijkTractorVerzekeringElements = new ZakelijkTractorVerzekeringElements();
export const apiMethods: ApiMethods = new ApiMethods();
export const klachtenFormulierElements: KlachtenFormulierElements = new KlachtenFormulierElements();
export const afspraakMakenElements: AfspraakMakenElements = new AfspraakMakenElements();
export const klantenserviceVraagStellenElements: KlantenserviceVraagStellenElements = new KlantenserviceVraagStellenElements();
export const schadeBeslisboomElements: SchadeBeslisboomElements = new SchadeBeslisboomElements();
export const situatieGewijzigdMethods: SituatieGewijzigdMethods = new SituatieGewijzigdMethods();
export const hmPageMijnUniveMethods: HmPageMijnUniveMethods = new HmPageMijnUniveMethods();
export const loginPageMethods: LoginPageMethods = new LoginPageMethods();
export const persoonlijkeGegevensElements: PersoonlijkeGegevensElements = new PersoonlijkeGegevensElements();
export const persoonlijkeGegevensMethods: PersoonlijkeGegevensMethods = new PersoonlijkeGegevensMethods();
export const mailhogMethods: MailhogMethods = new MailhogMethods();
export const verhuizingDoorgevenElements: VerhuizingDoorgevenElements = new VerhuizingDoorgevenElements();
export const correspondentieOverzichtElements: CorrespondentieElements = new CorrespondentieElements();
export const mijnSchadeEnClaimMethods: MijnSchadeEnClaimMethods = new MijnSchadeEnClaimMethods();
export const mijnVerzekeringElements: MijnVerzekeringenElements = new MijnVerzekeringenElements();
export const mijnVerzekeringenElements: MijnVerzekeringenElements = new MijnVerzekeringenElements();
export const alleVerzekeringenMethods: AlleVerzekeringenMethods = new AlleVerzekeringenMethods();
export const ongevallenVerzekeringMethods: OngevallenVerzekeringMethods = new OngevallenVerzekeringMethods();
export const hmPageMethods: HmPageMethods = new HmPageMethods();
export const kostbaarhedenVerzekeringElements: KostbaarhedenVerzekeringElements = new KostbaarhedenVerzekeringElements();
export const companyData: CompanyData = new CompanyData();
export const zorgeloosOnlineVerzekeringMethod: ZorgeloosOnlineVerzekeringMethods = new ZorgeloosOnlineVerzekeringMethods();
export const aansprakelijkheidsVerzekeringMethods: AansprakelijkheidsVerzekeringMethods = new AansprakelijkheidsVerzekeringMethods();
export const rechtsBijstandVerzekeringMethods: RechtsBijstandVerzekeringMethods = new RechtsBijstandVerzekeringMethods();
export const mopedElements: MopedElements = new MopedElements();
export const autoVerzekeringMethods: AutoVerzekeringMethods = new AutoVerzekeringMethods();
export const autoVerzekeringMethodsStepThreeAndFour: AutoVerzekeringMethodsStepThreeAndFour = new AutoVerzekeringMethodsStepThreeAndFour();
export const bikeElements: BikeElements = new BikeElements();
export const mopedMethods: MopedMethods = new MopedMethods();
export const licensePlateMethod: LicensePlateMethod = new LicensePlateMethod();
export const motorMethods: MotorMethods = new MotorMethods();
export const oldtimerVerzekeringMethods: OldtimerVerzekeringMethods = new OldtimerVerzekeringMethods();
export const scootMobielVerzekeringElements: ScootMobielVerzekeringElements = new ScootMobielVerzekeringElements();
export const bootVerzekeringMethods: BootVerzekeringMethods = new BootVerzekeringMethods();
export const boatWithName: BoatWithName = new BoatWithName();
export const camperVerzekeringMethods: CamperVerzekeringMethods = new CamperVerzekeringMethods();
export const caravanVerzekeringElements: CaravanVerzekeringElements = new CaravanVerzekeringElements();
export const reisVerzekeringMethods: ReisVerzekeringMethods = new ReisVerzekeringMethods();
export const alleVerzekeringenZakelijkMethods: AlleVerzekeringenZakelijkMethods = new AlleVerzekeringenZakelijkMethods();
export const aovZzpMethods: AovZzpMethods = new AovZzpMethods();
export const eigenVervoerVerzekeringMethods: EigenVervoerVerzekeringMethods = new EigenVervoerVerzekeringMethods();
export const roerendeZakenVerzekeringMethods: RoerendeZakenVerzekeringMethods = new RoerendeZakenVerzekeringMethods();
export const bedrijfsAutoVerzekeringMethods: BedrijfsAutoVerzekeringMethods = new BedrijfsAutoVerzekeringMethods();
export const zakelijkTractorVerzekerinigMethods: ZakelijkTractorVerzekeringMethods = new ZakelijkTractorVerzekeringMethods();

