import {MijnVerzekeringenElements} from "../pageobjects/mijnUniveParticulier/mijnVerzekeringen/mijnVerzekeringenElements";
import {KlachtenFormulierElements} from "../pageobjects/Klantenservice/KlachtenFormulierElements";
import {AfspraakMakenElements} from "../pageobjects/Klantenservice/AfspraakMakenElements";
import {KlantenserviceVraagStellenElements} from "../pageobjects/Klantenservice/KlantenserviceVraagStellenElements";
import {SchadeBeslisboomElements} from "../pageobjects/Klantenservice/SchadeBeslisboomElements";
import {PersoonlijkeGegevensElements} from "../pageobjects/mijnUniveParticulier/mijnGegevens/persoonlijkeGegevensElements";
import {VerhuizingDoorgevenElements} from "../pageobjects/mijnUniveParticulier/mijnGegevens/verhuizingDoorgevenElements";
import {CorrespondentieElements} from "../pageobjects/mijnUniveParticulier/MijnPostvak/CorrespondentieElements";
import {HmPageMijnUniveElements} from "../pageobjects/generic/hmPageMijnUniveElements";
import {SituatieGewijzigdElements} from "../pageobjects/Klantenservice/SituatieGewijzigdElements";
import {LoginPageElements} from "../pageobjects/mijnUniveParticulier/loginPage/loginPageElements";
import {MijnUniveAccountElements} from "../pageobjects/mijnUniveParticulier/mijnUniveAccount/mijnUniveAccountElements";
import {MijnSchadeEnClaimElements} from "../pageobjects/mijnUniveParticulier/MijnSchadeEnClaim/MijnSchadeEnClaimElements";
import {ApiElements} from "../pageobjects/api/apiElements";
import {HmPageElements} from "../pageobjects/generic/hmPageElements";

export const mijnVerzekeringElements: MijnVerzekeringenElements = new MijnVerzekeringenElements();
export const mijnVerzekeringenElements: MijnVerzekeringenElements = new MijnVerzekeringenElements();
export const klachtenFormulierElements: KlachtenFormulierElements = new KlachtenFormulierElements();
export const afspraakMakenElements: AfspraakMakenElements = new AfspraakMakenElements();
export const klantenserviceVraagStellenElements: KlantenserviceVraagStellenElements = new KlantenserviceVraagStellenElements();
export const schadeBeslisboomElements: SchadeBeslisboomElements = new SchadeBeslisboomElements();
export const persoonlijkeGegevensElements: PersoonlijkeGegevensElements = new PersoonlijkeGegevensElements();
export const verhuizingDoorgevenElements: VerhuizingDoorgevenElements = new VerhuizingDoorgevenElements();
export const correspondentieOverzichtElements: CorrespondentieElements = new CorrespondentieElements();
export const hmPageMijnUniveElements: HmPageMijnUniveElements = new HmPageMijnUniveElements();
export const situatieGewijzigdElements: SituatieGewijzigdElements = new SituatieGewijzigdElements();
export const loginPageElements: LoginPageElements = new LoginPageElements();
export const mijnUniveAccountElements: MijnUniveAccountElements = new MijnUniveAccountElements();
export const mijnSchadeEnClaimElements: MijnSchadeEnClaimElements = new MijnSchadeEnClaimElements();
export const apiElements: ApiElements = new ApiElements();
export const hmPageElements: HmPageElements = new HmPageElements();
