import {BicycleElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/bicycleElements';
import {ScootMobielVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/scootMobielVerzekeringElements';
import {CaravanVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/caravanVerzekeringElements';
import {KostbaarhedenVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/huisVerzekeringen/kostbaarhedenVerzekeringElements';
import {VehicleElements} from '../pageobjects/generic/vehicleElements';
import {MotorcycleElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/motorcycleElements';
import {OldtimerVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/oldtimerVerzekeringElements';
import {BootVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/bootVerzekeringElements';
import {MobileHomeVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/mobileHomeVerzekeringElements';
import {AlleVerzekeringenElements} from '../pageobjects/particuliereVerzekeringen/alleVerzekeringen/alleVerzekeringenElements';
import {OngevallenVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/gezondheidsVerzekeringen/ongevallenVerzekeringElements';
import {ZorgeloosOnlineVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/onlineVeiligheidVerzekeringen/zorgeloosOnlineVerzekeringElements';
import {AansprakelijkheidsVerzekerElements} from '../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/aansprakelijkheidsVerzekerElements';
import {RechtsBijstandVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/rechtsBijstandVerzekeringElements';
import {AutoVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElements';
import {AutoVerzekeringElementsStepThree} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElementsStepThree';
import {WoonVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/huisVerzekeringen/woonVerzekeringElements';
import {ReisVerzekeringElements} from '../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/reisVerzekeringElements';
import {ZorgCheckToolElements} from '../pageobjects/zorg/zorgCheckToolElements';
import {ZorgWizardElements} from '../pageobjects/zorg/zorgWizardElements';
import {SchadeServiceElements} from '../pageobjects/Klantenservice/SchadeServiceElements';
import {AnalyticsAutoverzekeringElements} from '../pageobjects/analytics/analyticsAutoverzekeringElements';
import {ZorgWizardCrossSellElements} from '../pageobjects/zorg/zorgWizardCrossSellElements';
import {KlantenserviceDirectOnlineRegelenElements} from '../pageobjects/Klantenservice/klantenserviceDirectOnlineRegelenElements';
import {VisualElements} from '../pageobjects/visual/visualElements';
import {KlantenserviceNeemContactOpElements} from '../pageobjects/Klantenservice/klantenserviceNeemContactOpElements';
import {WidgetsParticulierElements} from '../pageobjects/particuliereVerzekeringen/widgets/widgetsParticulierElements';
import {MopedElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/mopedElements';
import {MobileHomeElements} from '../pageobjects/particuliereVerzekeringen/transportVerzekeringen/MobileHomeElements';


export const bikeElements: BicycleElements = new BicycleElements();
export const scootMobielVerzekeringElements: ScootMobielVerzekeringElements = new ScootMobielVerzekeringElements();
export const caravanVerzekeringElements: CaravanVerzekeringElements = new CaravanVerzekeringElements();
export const kostbaarhedenVerzekeringElements: KostbaarhedenVerzekeringElements = new KostbaarhedenVerzekeringElements();
export const vehicleElements: VehicleElements = new VehicleElements();
export const motorcycleElements: MotorcycleElements = new MotorcycleElements();
export const oldtimerVerzekeringElements: OldtimerVerzekeringElements = new OldtimerVerzekeringElements();
export const bootVerzekeringElements: BootVerzekeringElements = new BootVerzekeringElements();
export const mobileHomeVerzekeringElements: MobileHomeVerzekeringElements = new MobileHomeVerzekeringElements();
export const alleVerzekeringenElements: AlleVerzekeringenElements = new AlleVerzekeringenElements();
export const ongevallenVerzekeringElements: OngevallenVerzekeringElements = new OngevallenVerzekeringElements();
export const zorgeloosOnlineVerzekeringElements: ZorgeloosOnlineVerzekeringElements = new ZorgeloosOnlineVerzekeringElements();
export const aansprakelijkheidsVerzekeringElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const rechtsBijstandVerzekeringElements: RechtsBijstandVerzekeringElements = new RechtsBijstandVerzekeringElements();
export const autoVerzekeringElements: AutoVerzekeringElements = new AutoVerzekeringElements();
export const autoVerzekeringElementsStepThree: AutoVerzekeringElementsStepThree = new AutoVerzekeringElementsStepThree();
export const woonVerzekeringElements: WoonVerzekeringElements = new WoonVerzekeringElements();
export const aansprakelijkheidsVerzekerElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const reisVerzekeringElements: ReisVerzekeringElements = new ReisVerzekeringElements();
export const zorgCheckToolElements: ZorgCheckToolElements = new ZorgCheckToolElements();
export const zorgWizardElements: ZorgWizardElements = new ZorgWizardElements();
export const schadeServiceElements: SchadeServiceElements = new SchadeServiceElements();
export const analyticsAutoverzekeringElements: AnalyticsAutoverzekeringElements = new AnalyticsAutoverzekeringElements();
export const zorgWizardCrossSellElements: ZorgWizardCrossSellElements = new ZorgWizardCrossSellElements();
export const visualElements: VisualElements = new VisualElements();
export const klantenserviceDirectOnlineRegelenElements: KlantenserviceDirectOnlineRegelenElements = new KlantenserviceDirectOnlineRegelenElements();
export const klantenserviceNeemContactOpElements: KlantenserviceNeemContactOpElements = new KlantenserviceNeemContactOpElements();
export const widgetsParticulierElements: WidgetsParticulierElements = new WidgetsParticulierElements();
export const mopedElements: MopedElements = new MopedElements();
export const mobileHomeElements: MobileHomeElements = new MobileHomeElements();
