import {BikeElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/bikeElements";
import {ScootMobielVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/scootMobielVerzekeringElements";
import {CaravanVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/caravanVerzekeringElements";
import {KostbaarhedenVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/huisVerzekeringen/kostbaarhedenVerzekeringElements";
import {VehicleElements} from "../pageobjects/generic/vehicleElements";
import {MotorElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/motorElements";
import {OldtimerVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/oldtimerVerzekeringElements";
import {BootVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/bootVerzekeringElements";
import {CamperVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/camperVerzekeringElements";
import {AlleVerzekeringenElements} from "../pageobjects/particuliereVerzekeringen/alleVerzekeringen/alleVerzekeringenElements";
import {OngevallenVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/gezondheidsVerzekeringen/ongevallenVerzekeringElements";
import {ZorgeloosOnlineVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/onlineVeiligheidVerzekeringen/zorgeloosOnlineVerzekeringElements";
import {AansprakelijkheidsVerzekerElements} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/aansprakelijkheidsVerzekerElements";
import {RechtsBijstandVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/rechtVerzekeringen/rechtsBijstandVerzekeringElements";
import {AutoVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElements";
import {AutoVerzekeringElementsStepThree} from "../pageobjects/particuliereVerzekeringen/transportVerzekeringen/autoVerzekeringElementsStepThree";
import {WoonVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/huisVerzekeringen/woonVerzekeringElements";
import {ReisVerzekeringElements} from "../pageobjects/particuliereVerzekeringen/vrijeTijdsVerzekeringen/reisVerzekeringElements";
import {ZorgCheckToolElements} from "../pageobjects/zorg/zorgCheckToolElements";
import {ZorgWizardElements} from "../pageobjects/zorg/zorgWizardElements";
import {SchadeServiceElements} from "../pageobjects/Klantenservice/SchadeServiceElements";
import {AnalyticsAutoverzekeringElements} from "../pageobjects/analytics/analyticsAutoverzekeringElements";

export const bikeElements: BikeElements = new BikeElements();
export const scootMobielVerzekeringElements: ScootMobielVerzekeringElements = new ScootMobielVerzekeringElements();
export const caravanVerzekeringElements: CaravanVerzekeringElements = new CaravanVerzekeringElements();
export const kostbaarhedenVerzekeringElements: KostbaarhedenVerzekeringElements = new KostbaarhedenVerzekeringElements();
export const vehicleElements: VehicleElements = new VehicleElements();
export const motorElements: MotorElements = new MotorElements();
export const oldtimerVerzekeringElements: OldtimerVerzekeringElements = new OldtimerVerzekeringElements();
export const bootVerzekeringElements: BootVerzekeringElements = new BootVerzekeringElements();
export const camperVerzekeringElements: CamperVerzekeringElements = new CamperVerzekeringElements();
export const alleVerzekeringenElements: AlleVerzekeringenElements = new AlleVerzekeringenElements();
export const ongevallenVerzekeringElements: OngevallenVerzekeringElements = new OngevallenVerzekeringElements();
export const zorgeloosOnlineVerzekeringElements: ZorgeloosOnlineVerzekeringElements = new ZorgeloosOnlineVerzekeringElements();
export const aansprakelijkheidsVerzekeringElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const rechtsBijstandVerzekeringElements: RechtsBijstandVerzekeringElements = new RechtsBijstandVerzekeringElements();
export const autoVerzekeringElements: AutoVerzekeringElements = new AutoVerzekeringElements();
export const autoVerzekeringElementsStepThree: AutoVerzekeringElementsStepThree = new AutoVerzekeringElementsStepThree();
export const woonVerzekeringElements: WoonVerzekeringElements = new WoonVerzekeringElements();
export const aansprakelijkheidsVerzekerElements: AansprakelijkheidsVerzekerElements = new AansprakelijkheidsVerzekerElements();
export const reisVerzekeringElements: ReisVerzekeringElements = new ReisVerzekeringElements();
export const zorgCheckToolElements: ZorgCheckToolElements = new ZorgCheckToolElements();
export const zorgWizardElements: ZorgWizardElements = new ZorgWizardElements();
export const schadeServiceElements: SchadeServiceElements = new SchadeServiceElements();
export const analyticsAutoverzekeringElements: AnalyticsAutoverzekeringElements = new AnalyticsAutoverzekeringElements();
