import {AlleVerzekeringenZakelijkElements} from "../pageobjects/zakelijkeVerzekeringen/alleVerzekeringen/alleVerzekeringenZakelijkElements";
import {ZakelijkAansprakelijkheidsVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/zakelijkAansprakelijkheidsVerzekeringElements";
import {RoerendeZakenVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsMiddelenVerzekeringen/roerendeZakenVerzekeringElements";
import {EigenVervoerVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/eigenVervoerVerzekeringElements";
import {ZakelijkTractorVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/zakelijkTractorVerzekeringElements";
import {BedrijfsAutoVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/mobiliteitsVerzekeringen/bedrijfsAutoVerzekeringElements";
import {ProductPageElements} from "../pageobjects/generic/productPageElements";
import {AovZzpElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/aovZzpElements";
import {ZakelijkRechtsBijstandVerzekeringElements} from "../pageobjects/zakelijkeVerzekeringen/bedrijfsActiviteitenVerzekeringen/zakelijkRechtsBijstandVerzekeringElements";
import {OndernemersScanElements} from "../pageobjects/zakelijkeVerzekeringen/ondernemersScan/ondernemersScanElements";

export const alleVerzekeringenZakelijkElements: AlleVerzekeringenZakelijkElements = new AlleVerzekeringenZakelijkElements();
export const zakelijkAansprakelijkheidsVerzekeringElements: ZakelijkAansprakelijkheidsVerzekeringElements = new ZakelijkAansprakelijkheidsVerzekeringElements();
export const roerendeZakenVerzekeringElements: RoerendeZakenVerzekeringElements = new RoerendeZakenVerzekeringElements();
export const eigenVervoerVerzekeringElements: EigenVervoerVerzekeringElements = new EigenVervoerVerzekeringElements();
export const zakelijkTractorVerzekeringElements: ZakelijkTractorVerzekeringElements = new ZakelijkTractorVerzekeringElements();
export const bedrijfsAutoVerzekeringElements: BedrijfsAutoVerzekeringElements = new BedrijfsAutoVerzekeringElements();
export const productPageElements: ProductPageElements = new ProductPageElements();
export const aovZzpElements: AovZzpElements = new AovZzpElements();
export const zakelijkRechtsBijstandVerzekeringElements: ZakelijkRechtsBijstandVerzekeringElements = new ZakelijkRechtsBijstandVerzekeringElements;
export const ondernemersScanElements: OndernemersScanElements = new OndernemersScanElements();
